import Foundation

/// Renders complete Tinker training scripts (SFT / DPO via tinker-cookbook)
/// into `runs/<name>/train.py`, ready to execute with the venv python.
enum TrainingTemplates {

    struct Config {
        var runName: String
        var baseModel: String = "Qwen/Qwen3-8B"
        var datasetPath: String
        var loraRank: Int = 32
        var learningRate: Double = 1e-4
        var epochs: Int = 1
        var kind: Kind = .sft

        enum Kind: String, CaseIterable, Identifiable {
            case sft = "SFT"
            case dpo = "DPO"
            var id: String { rawValue }
        }
    }

    /// Writes the rendered script and returns its URL.
    static func write(_ config: Config) throws -> URL {
        let directory = VenvManager.runsURL.appendingPathComponent(config.runName)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let script = config.kind == .sft ? sft(config) : dpo(config)
        let url = directory.appendingPathComponent("train.py")
        try script.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - SFT (tinker-cookbook supervised recipe)

    private static func sft(_ config: Config) -> String {
        """
        #!/usr/bin/env python3
        # Generated by SeerClient — supervised fine-tune via tinker-cookbook.
        # Dataset: JSONL rows of {"messages": [{"role", "content"}, ...]}
        import asyncio

        from tinker_cookbook import cli_utils
        from tinker_cookbook.recipes.chat_sl import train as chat_train
        from tinker_cookbook.supervised import train as sl_train


        def main():
            config = sl_train.Config(
                log_path="\(VenvManager.runsURL.path)/\(config.runName)/logs",
                model_name="\(config.baseModel)",
                dataset_builder=chat_train.ChatDatasetBuilderFromJsonl(
                    train_jsonl="\(config.datasetPath)",
                    model_name_for_tokenizer="\(config.baseModel)",
                ),
                lora_rank=\(config.loraRank),
                learning_rate=\(config.learningRate),
                num_epochs=\(config.epochs),
            )
            cli_utils.check_log_dir(config.log_path, behavior_if_exists="delete")
            asyncio.run(sl_train.main(config))


        if __name__ == "__main__":
            main()
        """
    }

    // MARK: - DPO (tinker-cookbook preference recipe)

    private static func dpo(_ config: Config) -> String {
        """
        #!/usr/bin/env python3
        # Generated by SeerClient — DPO preference tuning via tinker-cookbook.
        # Dataset: JSONL rows of {"prompt": [messages], "chosen": str, "rejected": str}
        # Pairs derive from Seer's Sinatra sentiment signals (Self-RLHF).
        import asyncio

        from tinker_cookbook import cli_utils
        from tinker_cookbook.preference import train_dpo


        def main():
            config = train_dpo.Config(
                log_path="\(VenvManager.runsURL.path)/\(config.runName)/logs",
                model_name="\(config.baseModel)",
                dataset_path="\(config.datasetPath)",
                lora_rank=\(config.loraRank),
                learning_rate=\(config.learningRate),
                num_epochs=\(config.epochs),
            )
            cli_utils.check_log_dir(config.log_path, behavior_if_exists="delete")
            asyncio.run(train_dpo.main(config))


        if __name__ == "__main__":
            main()
        """
    }
}
